services:
  app:
    build:
      context: .
      target: builder
    container_name: bugkhoji-backend
    restart: unless-stopped
    ports:
      - "3001:4000"
    env_file:
      - ./.env
    # environment:
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #   - DATABASE_USER=${DATABASE_USER}
    #   - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - bugkhoji_db
    volumes:
      - ./:/app

  bugkhoji_db:
    image: postgres:17.5-alpine3.22
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=bugkhoji
      - POSTGRES_PASSWORD=bugkhoji
      - POSTGRES_DB=bugkhoji
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
