services:
  app:
    build: .
    container_name: bugkhoji-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_HOST=${DATABASE_HOST}
    depends_on:
      - bugkhoji_db
    volumes:
      - ./:/app

  bugkhoji_db:
    image: postgres:17.5-alpine3.22
    container_name: postgres_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
